In [1]:
lst = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(lst)

In [4]:
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(3,)

In [7]:
arr.ndim

1

In [8]:
lst = np.arange(10)

In [9]:
lst

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [11]:
np.zeros

<function numpy.zeros>

In [12]:
np.zeros((9,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [16]:
a = np.ones(7)

In [24]:
a[:] = 9

In [25]:
a.astype(int)

array([9, 9, 9, 9, 9, 9, 9])

In [26]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [27]:
np.logspace(1,5,4)

array([1.00000000e+01, 2.15443469e+02, 4.64158883e+03, 1.00000000e+05])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.random.randn(8,9).max()

1.7864319696507742

In [30]:
np.random.rand(4)

array([0.78218096, 0.56285915, 0.14194026, 0.57735665])

In [38]:
arr

array([1, 2, 3])

In [39]:
arr.astype(float)

array([1., 2., 3.])

In [44]:
arr = arr.astype(str)

In [45]:
arr

array(['1', '2', '3'], dtype='<U11')

In [46]:
type(arr)

numpy.ndarray

In [47]:
arr.dtype

dtype('<U11')

In [49]:
a = np.arange(1,100,2).reshape(10,5)

In [50]:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [51]:
a[2:4,2:4]

array([[25, 27],
       [35, 37]])

In [52]:
a / 1

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [41., 43., 45., 47., 49.],
       [51., 53., 55., 57., 59.],
       [61., 63., 65., 67., 69.],
       [71., 73., 75., 77., 79.],
       [81., 83., 85., 87., 89.],
       [91., 93., 95., 97., 99.]])